### ISSUE TITLE
Blog about OLE

### ISSUE THREAD

**Issue by empeje** [ole-vi/treehouses.github.io.old#6]
I think some of our engineering efforts should be documented somewhere, and a blog is a good start. There there are some ideas

* Make my presentation about OLE in DevOpsDay Jakarta and MoodleMootPH18 as a blog
* Create a blog as a final report for interns

Any other idea?

I cc @dogi @xyb994  for his consideration and @sahilph for this thought as a current system engineering intern.

**Comment by empeje** [comment]
Example https://engineeringblog.yelp.com/2016/08/undebt-how-we-refactored-3-million-lines-of-code.html

**Comment by sahilph** [comment]
@mappuji Yes this sounds like a good idea. We should document it somewhere.

**Comment by empeje** [comment]
I'll bootstrap the blog soon

**Comment by empeje** [comment]
Solved in #10
