### ISSUE TITLE
potential security vulnerability

### ISSUE THREAD

**Issue by dogi** [ole-vi/treehouses.github.io.old#8]
https://github.com/treehouses/treehouses.github.io/network/dependencies
![a-20180501-071928](https://user-images.githubusercontent.com/13684059/39471269-51b88eb6-4d10-11e8-8f98-d31bbf19bf99.png)

**Comment by empeje** [comment]
Solved in #9 

<img width="1280" alt="screen shot 2018-05-08 at 11 01 42 pm" src="https://user-images.githubusercontent.com/11813607/39768553-d5e42aa2-5313-11e8-8fb5-481d970b8ca0.png">
